### PR TITLE
Fix a Couple Mixed Cluster Issues w/ Bucket Types

### LINKED ISSUE #492: Bucket Type Capability for Mixed Clusters Required
In mixed clusters where the claimant is a running a pre-2.0 version of Riak, some bucket type functions, when run on another node, will fail. In some cases, it will do so silently because of the [catch-all](https://github.com/basho/riak_core/blob/1.4.2/src/riak_core_claimant.erl#L208-L210) in `handle_call/2`.

To prevent this, any function in `riak_core_bucket_type` that contacts the claimant should be guarded by a capability. The following functions are affected:
- `create/2`
- `status/1`
- `activate/1`
- `update/2`
- `reset/1` -- although not exposed it should be guarded just in case

`get/1` does not need to be guarded because it only uses the local cluster metadata process on the node.

Example where `dev1` is running Riak 1.4.x and `dev2` is running Riak 2.0preX:

```
$ dev/dev2/bin/riak-admin bucket-type create type '{"props": {}}'
type created # nope it lies
$ dev/dev2/bin/riak-admin bucket-type status type
RPC to 'dev2@127.0.0.1' failed: {'EXIT',
                                 {function_clause,
                                  [{riak_kv_console,bucket_type_print_status,
                                    [<<"type">>,ok],
                                    [{file,"src/riak_kv_console.erl"},
                                     {line,451}]},
                                   {riak_kv_console,bucket_type_status,1,
                                    [{file,"src/riak_kv_console.erl"},
                                     {line,448}]},
                                   {rpc,'-handle_call_call/6-fun-0-',5,
                                    [{file,"rpc.erl"},{line,205}]}]}}
```

### PR DESCRIPTION
**Pull request by jrwest**
Fixes #492 & #493. 

For review, for now, testing by hand + running any existing tests (e.g. `btypes_eqc`) is the easiest way. I am working on extending the bucket types eqc test to cover these cases but didn't want to hold up this PR.

### CODE REVIEW

File: src/riak_core_bucket_type.erl [hunk 1]
```diff
@@ -141,15 +146,16 @@ defaults() ->
 create(?DEFAULT_TYPE, _Props) ->
     {error, default_type};
 create(BucketType, Props) when is_binary(BucketType) ->
-    riak_core_claimant:create_bucket_type(BucketType,
-                                          riak_core_bucket_props:merge(Props, defaults())).
+    ?IF_CAPABLE(riak_core_claimant:create_bucket_type(BucketType,
```
Comment (russelldb) [inline src/riak_core_bucket_type.erl:149]: I don't understand how this works…doesn't the first argument get evaluated anyway?

**Comment by russelldb** [comment]
Tested by hand. Works as advertised. I have a question as a comment above.

Also, when I start a node of 2.0 up, and a node of 1.4.6 up. And make a cluster of them, I get a flurry of errors reports:

```
10:53:32.548 [error] CRASH REPORT Process <0.895.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call({riak_core_metadata_hashtree,'dev1@127.0.0.1'}, {prefix_hash,{core,bucket_types}}, 1000) in gen_server:terminate/6 line 744
10:53:32.548 [error] gen_fsm <0.1523.0> in state ready terminated with reason: no such process or port in call to gen_server:call({riak_core_metadata_hashtree,'dev1@127.0.0.1'}, {prefix_hash,{core,bucket_types}}, 1000)
10:53:32.548 [error] gen_fsm <0.836.0> in state ready terminated with reason: no such process or port in call to gen_server:call({riak_core_metadata_hashtree,'dev1@127.0.0.1'}, {prefix_hash,{core,bucket_types}}, 1000)
```

File: src/riak_core_bucket_type.erl (hunk 1 above)
Comment (jrwest) [inline src/riak_core_bucket_type.erl:149]: no because the macros arguments are not evaluated just replaced. they are only evaluated when the case statement is at runtime. A quick example, using `io:format` shows this:

``` erlang
-module(mod).

-compile(export_all).

-define(M(X, Y), case random:uniform(5) < 2 of
                     true -> X;
                     false -> Y
                 end).

a() ->
    ?M(io:format("a~n"), io:format("b~n")).
```

```
11> mod:a().
b
ok
12> mod:a().
a
ok
```

**Comment by jrwest** [comment]
@russelldb those errors are cause by https://github.com/basho/yokozuna/issues/258. You can comment out the offending code in `riak_kv_vnode` to verify.

File: src/riak_core_bucket_type.erl (hunk 1 above)
Comment (russelldb) [inline src/riak_core_bucket_type.erl:149]: I am amaze.

**Comment by russelldb** [comment]
Thanks for the explanation. +1.
